### ISSUE TITLE
remove "<" and ">" in plugin.info.txt

### ISSUE THREAD

**Issue by e-dschungel** [ssahara/dw-plugin-commentsyntax#12]
Please remove "<" and ">" to make mailto link created by shortcode `~~INFO:syntaxplugins` (as used on wiki:syntax page) valid, currently the link is `<sahara.satoshi@gmail.com](mailto:sahara.satoshi@gmail.com)>`, see PR #11

**Comment by ssahara** [comment]
Thanks for report, fixed.
