### ISSUE TITLE
C言語スタイルコメントのみの行と、xbrプラグインとの適合性について (about compatibility with xbr plugin)

### ISSUE THREAD

**Issue by hokkaidoperson** [ssahara/dw-plugin-commentsyntax#5]
[xbrプラグイン](https://www.dokuwiki.org/plugin:xbr)とこのプラグインを同時に適用すると、改行が余計に挿入される事があります。

[こちらのページ](https://jdwiki.hkdyukkuri.space/videogrouptemplate)では、ページ冒頭にコメントのみの行を挿入しているのですが、どうやら、コメントを閉じた後の改行が無視されず出力されているようです（コメントのみの行については、行ごと無視される〈改行も出力しない〉のが望ましい）。
もしお手間でなければ対応頂けますでしょうか。よろしくお願いします。
（本当は「こうしたら上手く行きますよ」ってプルリクエストを送信したかったけど、手元では上手く行かなかったのでこの形でご勘弁下さい）

**Comment by ssahara** [comment]
CommentSyntax プラグイン側で対応するのは難しいです。というのは、
箇条書きの一部を一時的にコメントアウトしたいときに、item 2 行末改行を残す必要があるためです。
```
  * item 1
/** item 2  をコメントアウトするが、次はリストの継続として扱いたい */
  * item 3
```
xbr の代わりに [linebreak2](https://github.com/ssahara/dw-plugin-linebreak2) を使用してみてください。当方も同じような問題で困りましたので、独自に作成したプラグインです。 
インストール後、設定画面で renderer_xhtml をxbr から linebreak2 に切り替えてください。
また、linebreak2 の設定を適宜調整してみてください。

**Comment by hokkaidoperson** [comment]
回答ありがとうございます。

提示頂きましたlinebreak2プラグインをインストールし、設定を施したのですが、どこか上手く作動しないようなので、linebreak2側に改めてissueトピックを作成します。確認をお願いします。

**Comment by ssahara** [comment]
`/* ... */` のコメント構文について、余計な改行が発生しないように、 '/*'に先行する改行文字(`\n`)がある場合にはそれもマッチパターンに含めるようにするという案を思いつきました。
試していませんが、アイデアをメモしておきます。

    protected $pattern = array
            1 => '\n?/\*(?=.*?\*/)',
            4 => '\*/',
    }

**Comment by hokkaidoperson** [comment]
検討ありがとうございます。問題はとりあえず解決したので、一旦クローズしておきます。
